pipeline:
  identifier: Build_Miecznikk_python_1725365135998
  name: Build python
  orgIdentifier: default
  projectIdentifier: Default_Project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1725364771604
        repoName: Miecznikk/python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  name: run-commands-container
                  identifier: runcommandscontainer
                  template:
                    templateRef: testtemplate
                    templateInputs:
                      type: Run
                      spec:
                        connectorRef: <+input>
                        command: <+input>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
